import React, { useRef, useEffect, Suspense, useState } from 'react';
import { useGLTF, Html } from '@react-three/drei';
import WeatherPanel from './WeatherPanel';
import { fetchWeatherData, calculateEnergy } from './WeatherService';
import Environment from './Environment';
import CustomSky from './CustomSky';
import InputPanel from './InputPanel'; // Import InputPanel
import GroundPlane from './GroundPlane'; // Import GroundPlane

// SolarPanel component responsible for rendering each solar panel and handling click events
const SolarPanel = ({ position, id, onClick, energy }) => {
    const { scene } = useGLTF('/panel.glb'); // Load the 3D model of the solar panel
    const panelRef = useRef();

    useEffect(() => {
        const clone = scene.clone();
        panelRef.current.add(clone); // Add the cloned 3D model to the panel reference
    }, [scene]);

    return (
        <group
            ref={panelRef}
            position={position}
            onClick={(e) => {
                e.stopPropagation(); // Prevent event propagation
                onClick(id, energy); // Trigger the onClick event with the panel ID and energy
            }}
        />
    );
};

// Main component that manages the solar panels, weather data, and environment
const SolarPanelWrapper = () => {
    const [selectedPanel, setSelectedPanel] = useState(null); // State to track the selected panel ID
    const [selectedPanelEnergy, setSelectedPanelEnergy] = useState(null); // State to track the selected panel's energy
    const [weatherData, setWeatherData] = useState(null); // State to store fetched weather data
    const [currentEnergy, setCurrentEnergy] = useState(0); // State to track the current energy generated by panels
    const [weatherCode, setWeatherCode] = useState(); // State to store the current weather code
    const [panels, setPanels] = useState([]); // State to store the array of solar panels
    const [localTime, setLocalTime] = useState(''); // State to store the local time from weather data

    const [panelConfig, setPanelConfig] = useState({
        latitude: 13,
        longitude: 77,
        efficiency: 0.15,
        area: 1.6
    });

    // Fetch weather data and calculate energy based on panel configuration
    useEffect(() => {
        const fetchData = async () => {
            try {
                const data = await fetchWeatherData(panelConfig.latitude, panelConfig.longitude);
                setWeatherData(data); // Update weather data state
                const energy = calculateEnergy(data.ghi, panelConfig.efficiency, panelConfig.area);
                setWeatherCode(data.weatherCode); // Update weather code state
                setCurrentEnergy(energy); // Update current energy state
                setLocalTime(data.localTime); // Update local time state
            } catch (error) {
                console.error('Error fetching weather data:', error);
            }
        };

        fetchData();
        const interval = setInterval(fetchData, 900000); // Fetch weather data every 15 minutes
        return () => clearInterval(interval); // Clear interval on component unmount
    }, [panelConfig]);

    // Initialize solar panels and position them in a grid
    useEffect(() => {
        const rows = 4;
        const cols = 5;
        const spacing = 3.5; // Adjust spacing between panels

        const newPanels = [];
        for (let row = 0; row < rows; row++) {
            for (let col = 0; col < cols; col++) {
                const id = `${row}-${col}`;
                newPanels.push(
                    <SolarPanel
                        key={id}
                        id={id}
                        position={[col * spacing * 2, 0, row * spacing]} // Position panels in a grid
                        onClick={(id) => {
                            setSelectedPanel(id); // Set the selected panel ID on click
                            setSelectedPanelEnergy(currentEnergy); // Set the selected panel's energy
                        }}
                        energy={currentEnergy}
                        localTime={localTime}
                    />
                );
            }
        }
        setPanels(newPanels); // Update the panels state with the newly created panels
    }, [currentEnergy]);

    // Handle updates to the panel configuration (latitude, longitude, efficiency, area)
    const handleConfigUpdate = (newConfig) => {
        setPanelConfig(newConfig);
    };

    // Styling for the panel details HTML overlay
    const styles = {
        panel: {
            position: 'absolute',
            top: '10px',
            left: '10px',
            padding: '20px',
            backgroundColor: 'rgba(255, 255, 255, 0.9)',
            borderRadius: '12px',
            boxShadow: '0 6px 12px rgba(0, 0, 0, 0.2)',
            width: '250px',
            fontFamily: 'Arial, sans-serif',
            color: '#333',
            border: '1px solid #ddd'
        },
        title: {
            margin: '0 0 15px 0',
            fontSize: '22px',
            color: '#444',
            fontWeight: 'bold',
            textAlign: 'center'
        },
        text: {
            margin: '10px 0',
            fontSize: '16px',
            lineHeight: '1.5'
        },
        button: {
            display: 'block',
            marginTop: '15px',
            backgroundColor: '#007bff',
            color: '#fff',
            border: 'none',
            padding: '10px 15px',
            borderRadius: '8px',
            cursor: 'pointer',
            fontSize: '16px',
            textAlign: 'center',
            transition: 'background-color 0.3s ease',
            width: '100%'
        },
        buttonHover: {
            backgroundColor: '#0056b3'
        }
    };

    return (
        <Suspense fallback={null}>
            <ambientLight intensity={0.2} /> {/* Ambient lighting for the scene */}

            {panels} {/* Render the array of solar panels */}

            <GroundPlane position={[0, -0.05, 0]} /> {/* Ground plane for the scene */}

            <InputPanel position={[0, 5, -10]} onSubmit={handleConfigUpdate} /> {/* Input panel for updating solar panel configuration */}

            <Environment weatherCode={weatherCode} /> {/* Render the environment based on the weather code */}

            {weatherData && (<WeatherPanel position={[-12, 5, -10]} weatherData={weatherData} /> )} {/* Display weather data in a panel */}

            {weatherData && weatherData.localTime && (<CustomSky time={weatherData.localTime} /> )}{/* Render the sky based on the local time */}

            {selectedPanel && (
                <Html>
                    <div style={styles.panel}>
                        <h2 style={styles.title}>Panel Details</h2>
                        <p style={styles.text}>Selected Panel ID: <strong>{selectedPanel}</strong></p>
                        <p style={styles.text}>Energy Generated: <strong>{selectedPanelEnergy !== null ? selectedPanelEnergy.toFixed(2) : 'N/A'} W-h</strong></p>
                        <button style={styles.button} onClick={() => {
                            setSelectedPanel(null); // Deselect the panel on close button click
                            setSelectedPanelEnergy(null); // Clear the selected panel's energy
                        }}>Close</button>
                    </div>
                </Html>
            )}
        </Suspense>
    );
};

export default SolarPanelWrapper;
